// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Api.Models
{
    //public partial class RequestType
    //{
    //    public RequestType()
    //    {
    //        Request = new HashSet<Request>();
    //    }

    //    public int Id { get; set; }
    //    public string Name { get; set; }

    //    public virtual ICollection<Request> Request { get; set; }
    //}
    public  class RequestType
    {
        private RequestType()
        {
            //Need for EF
        }
        public RequestType(string name)
        {
            Name = name;
        }

        public int Id { get; private set; }
        public string Name { get; private set; }

        public List<Request> Request { get; private set; }
    }

}